import { translateText } from "./translation";

export const wordCategories: Record<string, string[]> = {
  Food: [
    "Pizza",
    "Apple",
    "Bread",
    "Cake",
    "Ice Cream",
    "Banana",
    "Sandwich",
    "Milk",
    "Cookie",
    "Cheese",
    "Spaghetti",
    "Hamburger",
    "Popcorn",
    "Salad",
    "Muffin",
    "Taco",
    "Yogurt",
    "Cereal",
    "Peanut Butter",
    "Chicken",
    "Croissant",
    "Quiche",
    "Sushi",
    "Ravioli",
    "Guacamole",
    "Eggplant",
    "Avocado",
    "Falafel",
    "Pomegranate",
    "Wasabi",
  ],
  Animals: [
    "Dog",
    "Cat",
    "Cow",
    "Fish",
    "Horse",
    "Duck",
    "Bird",
    "Pig",
    "Rabbit",
    "Lion",
    "Elephant",
    "Giraffe",
    "Kangaroo",
    "Panda",
    "Penguin",
    "Zebra",
    "Bear",
    "Monkey",
    "Snake",
    "Dolphin",
    "Armadillo",
    "Platypus",
    "Narwhal",
    "Chameleon",
    "Wombat",
    "Axolotl",
    "Sloth",
    "Tarantula",
    "Iguana",
    "Hedgehog",
  ],
  "Movies & TV": [
    "Frozen",
    "Toy Story",
    "Spider-Man",
    "Minions",
    "Batman",
    "Cars",
    "Moana",
    "Shrek",
    "Harry Potter",
    "Star Wars",
    "Jurassic Park",
    "Finding Nemo",
    "Black Panther",
    "Aladdin",
    "Lion King",
    "Home Alone",
    "E.T.",
    "Cinderella",
    "Encanto",
    "Up",
    "Inception",
    "Casablanca",
    "The Godfather",
    "Parasite",
    "Interstellar",
    "Schindler's List",
    "Amélie",
    "Jaws",
    "Titanic",
    "La La Land",
  ],
  "Sports & Games": [
    "Soccer",
    "Basketball",
    "Baseball",
    "Football",
    "Tennis",
    "Hockey",
    "Golf",
    "Swimming",
    "Running",
    "Volleyball",
    "Badminton",
    "Bowling",
    "Rugby",
    "Skateboarding",
    "Surfing",
    "Lacrosse",
    "Karate",
    "Gymnastics",
    "Archery",
    "Dodgeball",
    "Polo",
    "Curling",
    "Fencing",
    "Equestrian",
    "Biathlon",
    "Triathlon",
    "Javelin",
    "Bocce",
    "Squash",
    "Cricket",
  ],
  Places: [
    "School",
    "Park",
    "Beach",
    "Home",
    "Zoo",
    "Farm",
    "Playground",
    "Mall",
    "Hospital",
    "Library",
    "City Hall",
    "Stadium",
    "Airport",
    "Theater",
    "Aquarium",
    "Museum",
    "Restaurant",
    "Castle",
    "Mountain",
    "Bridge",
    "Pyramids",
    "Eiffel Tower",
    "Great Wall",
    "Taj Mahal",
    "Colosseum",
    "Machu Picchu",
    "Stonehenge",
    "Sydney Opera House",
    "Statue of Liberty",
    "Mount Everest",
  ],
  "Jobs & Professions": [
    "Teacher",
    "Doctor",
    "Chef",
    "Farmer",
    "Nurse",
    "Firefighter",
    "Police Officer",
    "Singer",
    "Athlete",
    "Pilot",
    "Librarian",
    "Engineer",
    "Lawyer",
    "Dancer",
    "Mechanic",
    "Scientist",
    "Actor",
    "Author",
    "Soldier",
    "Baker",
    "Archaeologist",
    "Astronomer",
    "Mathematician",
    "Fashion Designer",
    "Diplomat",
    "Geologist",
    "Biologist",
    "Sculptor",
    "Politician",
    "Architect",
  ],
  "Objects & Things": [
    "Ball",
    "Chair",
    "Book",
    "Phone",
    "Bed",
    "Table",
    "Shoes",
    "Hat",
    "Pen",
    "Clock",
    "Backpack",
    "Camera",
    "Guitar",
    "Bicycle",
    "Umbrella",
    "Mirror",
    "Radio",
    "Blanket",
    "Suitcase",
    "Microwave",
    "Telescope",
    "Typewriter",
    "Microscope",
    "Projector",
    "Compass",
    "Thermometer",
    "Accordion",
    "Saxophone",
    "Sewing Machine",
    "Drone",
  ],
  Vehicles: [
    "Car",
    "Bus",
    "Bike",
    "Boat",
    "Truck",
    "Train",
    "Plane",
    "Taxi",
    "Van",
    "Scooter",
    "Helicopter",
    "Motorcycle",
    "Sailboat",
    "Tractor",
    "Submarine",
    "Jeep",
    "Limousine",
    "Hot Air Balloon",
    "Skateboard",
    "Rocket",
    "Segway",
    "Monorail",
    "Rickshaw",
    "Gondola",
    "Hovercraft",
    "Cable Car",
    "Zeppelin",
    "Tuk Tuk",
    "Snowmobile",
    "Amphibious Vehicle",
  ],
  Holidays: [
    "Birthday",
    "Christmas",
    "Halloween",
    "Easter",
    "New Year",
    "Thanksgiving",
    "Wedding",
    "Graduation",
    "Valentine's Day",
    "Party",
    "Fireworks",
    "Parade",
    "Pumpkin",
    "Santa Claus",
    "Hanukkah",
    "Costume",
    "Gift",
    "Balloon",
    "Turkey",
    "Piñata",
    "Diwali",
    "Ramadan",
    "Kwanzaa",
    "Lantern Festival",
    "Oktoberfest",
    "Mardi Gras",
    "Passover",
    "Holi",
    "Cinco de Mayo",
  ],
  School: [
    "Teacher",
    "Desk",
    "Book",
    "Pencil",
    "Eraser",
    "Notebook",
    "Ruler",
    "Backpack",
    "Lunch",
    "Bus",
    "Calculator",
    "Globe",
    "Blackboard",
    "Test",
    "Science",
    "History",
    "Dictionary",
    "Marker",
    "Recess",
    "Homework",
    "Microscope",
    "Thesis",
    "Graduation",
    "Laboratory",
    "Debate",
    "Scholarship",
    "Periodic Table",
    "Geometry",
    "Physics",
    "Biology",
  ],
  "Silly & Random": [
    "Banana Peel",
    "Unicorn",
    "Slime",
    "Chicken Nugget",
    "Bubble",
    "Robot",
    "Pickle",
    "Mustache",
    "Toilet",
    "Rubber Chicken",
    "Disco Ball",
    "Llama",
    "Kazoo",
    "Waffle",
    "Flamingo",
    "Donut",
    "Pirate",
    "Dinosaur Costume",
    "Taco Truck",
    "Whoopee Cushion",
    "Platypus",
    "Loch Ness Monster",
    "Yeti",
    "Marshmallow Cannon",
    "Giant Rubber Duck",
    "Sasquatch",
    "UFO",
    "Time Machine",
  ],
  Fantasy: [
    "Dragon",
    "Fairy",
    "Wizard",
    "Giant",
    "Mermaid",
    "Troll",
    "Elf",
    "Unicorn",
    "Witch",
    "Knight",
    "Griffin",
    "Phoenix",
    "Centaur",
    "Minotaur",
    "Pegasus",
    "Cyclops",
    "Goblin",
    "Genie",
    "Werewolf",
    "Vampire",
    "Chimera",
    "Kraken",
    "Basilisk",
    "Hydra",
    "Leviathan",
    "Banshee",
    "Sphinx",
    "Thunderbird",
    "Golem",
    "Djinn",
  ],
  Technology: [
    "Phone",
    "Laptop",
    "TV",
    "Headphones",
    "Camera",
    "Tablet",
    "Mouse",
    "Keyboard",
    "Watch",
    "Remote",
    "Drone",
    "Printer",
    "Microphone",
    "Projector",
    "Smartwatch",
    "Video Game",
    "Calculator",
    "Telescope",
    "Robot",
    "Flashlight",
    "3D Printer",
    "Virtual Reality",
    "Quantum Computer",
    "Satellite",
    "Supercomputer",
    "Nanobot",
    "Hoverboard",
    "AI Assistant",
    "Hologram",
  ],
  Nature: [
    "Tree",
    "Rock",
    "River",
    "Sun",
    "Moon",
    "Flower",
    "Grass",
    "Mountain",
    "Cloud",
    "Leaf",
    "Volcano",
    "Glacier",
    "Canyon",
    "Desert",
    "Jungle",
    "Waterfall",
    "Ocean",
    "Storm",
    "Rainbow",
    "Cave",
    "Aurora Borealis",
    "Tsunami",
    "Earthquake",
    "Meteor",
    "Eclipse",
    "Black Hole",
    "Sandstorm",
    "Tornado",
    "Coral Reef",
    "Fossil",
  ],
  Music: [
    "Guitar",
    "Piano",
    "Song",
    "Dance",
    "Singer",
    "Drum",
    "Radio",
    "Movie",
    "Game",
    "Stage",
    "Violin",
    "Trumpet",
    "DJ",
    "Orchestra",
    "Actor",
    "Musical",
    "Karaoke",
    "Popcorn",
    "Audience",
    "Costume",
    "Didgeridoo",
    "Harpsichord",
    "Theremin",
    "Sitar",
    "Bagpipes",
    "Sousaphone",
    "Ballet",
    "Opera",
    "Mime",
    "Shakespeare",
  ],
};

export function getRandomWord(category: string, language = "en"): string {
  const words = wordCategories[category];
  let selectedWord: string;

  if (!words || words.length === 0) {
    // Fallback to a random category if the specified one doesn't exist
    const categories = Object.keys(wordCategories);
    const randomCategory =
      categories[Math.floor(Math.random() * categories.length)];
    const fallbackWords = wordCategories[randomCategory];
    selectedWord =
      fallbackWords[Math.floor(Math.random() * fallbackWords.length)];
  } else {
    selectedWord = words[Math.floor(Math.random() * words.length)];
  }

  // Translate the word if language is not English
  if (language !== "en") {
    return translateText(selectedWord, language);
  }

  return selectedWord;
}

export function getRandomWordFromRandomCategory(language = "en"): {
  word: string;
  category: string;
} {
  const categories = Object.keys(wordCategories);
  const randomCategory =
    categories[Math.floor(Math.random() * categories.length)];
  const words = wordCategories[randomCategory];
  const randomWord = words[Math.floor(Math.random() * words.length)];

  // Translate the word if language is not English
  const translatedWord =
    language !== "en" ? translateText(randomWord, language) : randomWord;

  return {
    word: translatedWord,
    category: randomCategory,
  };
}

export function translateCategoryName(
  category: string,
  language: string,
): string {
  if (language === "en") return category;
  return translateText(category, language);
}
